### ISSUE TITLE
read this if you want to port this to edge & chrome

### ISSUE THREAD

**Issue by bangbangyouall** [lightbeam24/CustomTube#1]
https://blog.shahednasser.com/chrome-extension-tutorial-migrating-to-manifest-v3-from-v2

**Comment by lightbeam24** [comment]
Yeah, I know there's guides on how to do it. Thing is, while I can't remember where I read this, apparently Firefox doesn't fully support Manifest V3 yet. It wouldn't surprise me, Manifest V3 wasn't supported in Firefox _at all_ when CustomTube development started, which is why I went with V2 in the first place. So I would probably at least want to wait until Firefox mostly if not fully supports Manifest V3 to port it.

**Comment by bangbangyouall** [comment]
you can leave the manifest v2 version to firefox & make a duplicate version for chrome & edge

**Comment by lightbeam24** [comment]
Sorry, but I won't be doing that. It's way too much work for browsers I literally never use (the main reason I made this extension in the first place is so I can use it). It'll just have to wait. I'll have to port it to Manifest V3 eventually, Firefox won't support V2 forever.

**Comment by bangbangyouall** [comment]
nvm i am already making an edge port of this extension using this guide, what image domain does youtube use?

**Comment by lightbeam24** [comment]
If you're going to make a personal Edge port for yourself, then I wouldn't even bother with Manifest V3. You can still load Manifest V2 extensions in Edge through developer mode.

**Comment by bangbangyouall** [comment]
the extension itself works, but not the theming.

**Comment by lightbeam24** [comment]
Sorry, but I would prefer if you didn't. I put alot of work into it, so if it's going on those stores I'd like it to be done by me. And I WILL put it on those stores eventually. If you wanna release it on Github that's fine though.

**Comment by lightbeam24** [comment]
Please don't. I put alot of work into it, so if it's going on those stores I'd like it to be done by me, where I can be sure everything is working correctly. And I WILL put it on those stores eventually. If you wanna release it on Github that's fine though.

The big reason though: I have a vision for CustomTube. I don't want to release a Chromium version until the extension has the 2011 layout. See, the original vision for CustomTube's initial release was to include all layouts from 2011-2023. But it was taking too long, so I released an early version on Firefox exclusively, simply because it's the browser I use. But I don't want this early version to go onto stores of much more popular browsers. **I want to make sure this extension is the best it can be before making a Chrome Web Store version, because that version will be used by way more people.** Sorry I didn't mention this earlier.

Don't worry, the 2011 layout won't take forever. It had to be cut from the extension's code for reasons, but I can add it back with relative ease, I would just need to optimize the code to fit in with the new codebase. Here's what the 2011 layout looked like, pretty far along already: https://imgur.com/a/1OW5ioP

**Comment by bangbangyouall** [comment]
k

**Comment by kena006** [comment]
ive succesfully changed it to manifest v3 but it still doesnt work.

**Comment by kena006** [comment]
this is a huge problem that it doesnt work on chrome because chrome is literally the most used web browser.

**Comment by lightbeam24** [comment]
> this is a huge problem that it doesnt work on chrome because chrome is literally the most used web browser.

It doesn't work in Chrome because it is a *Firefox* extension that wasn't tested in any Chromium based browser. There's probably tons of issues that will need to be fixed for a Chromium port.

Here is the current plan: https://github.com/lightbeam24/customtube/issues/15#issuecomment-1570295753

**Comment by lightbeam24** [comment]
The Chrome version is now in beta if any of you would like to try it out: https://github.com/lightbeam24/CustomTube/releases/tag/Beta

**Comment by lightbeam24** [comment]
I have submitted the Chrome Web Store version for review. I will consider putting it on the Edge Addons Store at later date, as Chrome's addon submission process was surprisingly lengthy compared to Firefox's, and it looks like Edge's might be as well.
