### ISSUE TITLE
Video end cards and player sometimes do not resize to the current video resolution

### ISSUE THREAD

**Issue by UnderscoreAngel** [lightbeam24/CustomTube#11]
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/08221978-bfc8-4bc3-8e6e-b3ccf03c2959)
ouch!

**Comment by lightbeam24** [comment]
Is it fixed by going into fullscreen or zooming in/out?

**Comment by UnderscoreAngel** [comment]
> Is it fixed by going into fullscreen or zooming in/out?

i haven't tried, when it happens i will try to see if it changes

**Comment by lightbeam24** [comment]
Looks like you're using a script that changes the player. Maybe that has something to do with it?

**Comment by UnderscoreAngel** [comment]
> Looks like you're using a script that changes the player. Maybe that has something to do with it?

i've already replied on discord abt this lol, but no, the normal player do this same thing, i've took a look at the main.js file, tweaked somethings, still doesn't work :(

**Comment by lightbeam24** [comment]
Yeah, I'm not sure how to fix it. Once I'm better at JavaScript I might try to improve it. Not much I can do about it now.

**Comment by lightbeam24** [comment]
In 1.2.3 I changed it so it fires the resizing code on an interval, which was needed because the code was partially reliant on the old watch metadata still being present. It's not a perfect implementation by any means, but it should basically eliminate this issue (I'm starting to understand how the resizer works a little bit, so maybe I can improve it eventually).
